name: Deploy FastAPI

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            mkdir -p ~/app
            cd ~/app

            if [ -d ".git" ]; then
              git reset --hard
              git pull
            else
              git clone https://github.com/VD-git/oracle-api.git .
            fi

            sudo usermod -aG docker $SERVER_USER || true

            docker stop oracle-fastapi || true
            docker rm oracle-fastapi || true

            docker build -t oracle-fastapi .

            docker run -d -p 8000:8000 --name oracle-fastapi oracle-fastapi

            curl -L ${{ secrets.SERVER_HOST }}